# isaacsim path, gym environment, python path
# isaacsim path, gym environment, python path
gym:
  isaacsimpath : "/home/simonwsy/.local/share/ov/pkg/isaac_sim-2023.1.1"
  task : "Crazyflie"
  pythonpath : "~/.local/share/ov/pkg/isaac_sim-*/python.sh"
  scriptpath : "scripts/rlgames_train.py"
  headless : true
  extra : "--env-config-path ./config.yaml"
  multirun : false

# output path for simple eureka
output:
  path : "./results/{date}"
  overwrite : "/home/simonwsy/.local/share/ov/pkg/isaac_sim-2023.1.1/OmniIsaacGymEnvs/omniisaacgymenvs/tasks/crazyflie.py"

generation:
  number: 2
  epochs: 5

defaults:
  - _self_
  - api: moonshot