gym:
  omniisaacsimpathenv : "/home/simonwsy/.local/share/ov/pkg/isaac_sim-2023.1.1/OmniIsaacGymEnvs/omniisaacgymenvs"
  task : "Crazyflie"
  pythonpath : "/home/simonwsy/.local/share/ov/pkg/isaac_sim-2023.1.1/python.sh"
  scriptpath : "scripts/rlgames_train.py"
  headless : True
  enable_recording : False
  extra : ""
  multigpu : True
  max_iterations : 1000
  checkpoint: ''
  runs: .

# output path for simple eureka
output:
  path : "./results/{date}"
  overwrite : "/home/simonwsy/.local/share/ov/pkg/isaac_sim-2023.1.1/OmniIsaacGymEnvs/omniisaacgymenvs/tasks/crazyflie.py"

generation:
  chunk_size: 4 # No more than 5
  epochs: 1
  sample: 12
  run_all: True

critic_agent:
  enable: True
  name: "Alice"
  duty: "product manager"

actor_agent:
  enable: True
  name: "Bob"
  duty: "reward function designer"
  
env:
  success_keyword: "MAX EPOCHS NUM!"
  failure_keyword: Traceback

evaluation: True
iter: 0
idx: 0
result_dir: "latest"
checkpoint_name: "latest"
run_all: False
record_video: True
record_base_dir: "./videos"

defaults:
  - _self_
  - api: moonshot
  - task: double_flipping