# isaacsim path, gym environment, python path
gym:
  isaacsimpath : "H:/Omniverse/Library/isaac_sim-2023.1.1/OmniIsaacGymEnvs/omniisaacgymenvs"
  task : "Crazyflie"
  pythonpath : "H:/Omniverse/Library/isaac_sim-2023.1.1/python.bat"
  scriptpath : "scripts/rlgames_train.py"
  headless : True
  extra : "--env-config-path ./config.yaml"
  multigpu : False

# output path for simple eureka
output:
  path : "./results/{date}"
  overwrite : "H:\\Omniverse\\Library\\isaac_sim-2023.1.1\\OmniIsaacGymEnvs\\omniisaacgymenvs\\tasks\\crazyflie.py"

generation:
  number: 2
  epochs: 5
  run_all: True

defaults:
  - _self_
  - api: moonshot