# isaacsim path, gym environment, python path
gym:
  omniisaacsimpathenv : "H:/Omniverse/Library/isaac_sim-2023.1.1/OmniIsaacGymEnvs/omniisaacgymenvs"
  task : "Crazyflie"
  pythonpath : "H:/Omniverse/Library/isaac_sim-2023.1.1/python.bat"
  scriptpath : "scripts/rlgames_train.py"
  headless : True
  enable_recording : False
  extra : "--env-config-path ./config.yaml"
  multigpu : False

# output path for simple eureka
output:
  path : "./results/{date}"
  overwrite : "H:\\Omniverse\\Library\\isaac_sim-2023.1.1\\OmniIsaacGymEnvs\\omniisaacgymenvs\\tasks\\crazyflie.py"

generation:
  chunk_size: 4 # Default: 4
  epochs: 1
  sample: 10
  run_all: True

env:
  success_keyword: "MAX EPOCHS NUM!"
  failure_keyword: Traceback
defaults:
  - _self_
  - api: moonshot
  - task: double_flipping